version: "3.5"

services:
  mysql:
    image: mysql:8.0.26
    container_name: db-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=sasa
    ports:
    - 3308:3306
    networks:
    - red-wallpaper

networks:
  red-wallpaper:
    name: red-taller-wallpaper

